### ISSUE TITLE
Refactor user abilities for PBCore records

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#1041]
**rationale** the permission rules have been added to multiple times without a refactor, and there are some inconsistencies.

For instance, the idea of the `User#aapb_referer?` was to whitelist certain referers (e.g. popuparchive.com) but the ability `can?(:play)` was always failing for popuparchive.com referers for PBCore recrods marked as "protected". And yet, these two conditions were ANDed together in `MediaController` to determine whether or not to resolve Sony Ci URLs.

Another example is the `cannot :skip_tos` ability. This is hard to read with it's nand logic, and I'm not sure why the default is to allow skipping the TOS, and then adding in confusing conditions to disallow it. It would seem much clearer to have explicit conditions for `can :skip_tos`.

This ticket goes hand in hand with #1040.

**Done when**
- [ ] there is a clear and concise way to whitelist privileged referers that can view all content, and bypass the TOS.
- [ ] there is a clear and concise way to whitelist privileged IP ranges that can view all content, and bypass the TOS
- [ ] all other permission rules remain intact

**Comment by sroosa** [comment]
make a truth table!!!
