### ISSUE TITLE
Display different aspect ratios

### ISSUE THREAD

**Issue by cmhosale** [WGBH-MLA/AAPB2#1072]
We're beginning to create our own video proxies for new collections that are accessioned at WGBH and do not go through a digitization vendor. This means we're getting more variations in source material specifications and the resulting proxies than before. A new collection is comprised of raw footage shot in 16:10. I made proxies that are 16:10 aspect ratio, but the video player seems to be displaying it in a 4:3 box with some bars on it. I think we'd like the player to display larger but am unsure if that is possible. Thankfully the box is not presenting the video in the incorrect aspect ratio.

Please see here for an example:
http://americanarchive.org/catalog/cpb-aacip_507-0000000k7v

**Comment by caseyedavis12** [comment]
@afred can you work on this? We are hosting a meeting with the collection donor on December 7 (Ken Burns filmmaking company Florentine Films) so this really needs to be fixed by then.

Cc @muraszko
@cmhosale

**Comment by Muraszko** [comment]
@caseyedavis12 @afred 
Please hold off on this work until after the upcoming HydraDAM2 sprint.  Thanks

**Comment by afred** [comment]
@Muraszko 👍 - can we put together a milestone (or project?) in Github for AAPB tickets to tackle after this Hydradam sprint?

**Comment by afred** [comment]
@cmhosale @caseyedavis12 note that there is a "full screen" option for the video player. Is that sufficient, or do we want to increase the size of the player when it is not in "full screen" mode, and if so.. to what?

**Comment by afred** [comment]
**done when**
  * height and width of `<video>` are set to match the aspect ratio given in the PBCore element `/pbcoreDescriptionDocument/pbcoreInstantiation/instantiationEssenceTrack/essenceTrackAspectRatio`

**Comment by jasoncorum** [comment]
@cmhosale: As @afred mentioned earlier, the original link doesn't appear to exist. Is there another instance of a record with 16:10 video I can check out? Thanks!

**Comment by cmhosale** [comment]
@afred @jasoncorum Sorry about that, here is another example: http://americanarchive.org/catalog/cpb-aacip_509-js9h41kc8n

**Comment by caseyedavis12** [comment]
We are not going to work on this issue until Digital has provided mock-ups for new Record page layout as part of the Transcript IMLS project.

**Comment by caseyedavis12** [comment]
Comments from recently closed #1169:

"

Casey wrote:
Can we make the website draw a 16x9 player if this metadata field appears anywhere in the PBCore:
<essenceTrackFrameSize>720 x 486</essenceTrackFrameSize>

@jasoncorum: any work on this issue can be charged to Overhead 156840
 
Charles wrote:
http://americanarchive.org/catalog/cpb-aacip_504-222r49gp2h here is a 16x9 video. The player draws a hard coded 4:3 box and then letterboxes the video. It would be nice if the player responded to the video being 16x9 by drawing a bigger 16x9 player without letterboxes."

**Comment by cmhosale** [comment]
16:9 videos now display correctly in Chrome, but they display incorrectly in firefox. Please get them to display correctly in Firefox.
