### ISSUE TITLE
UX Rec: Only Display AAPB ID

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1143]
**Done when**
- [ ] Source values for local identifiers that appear as labels on asset records are pre-pended with "Local ID"

Example: 
IPTV Barcode: IPTVUS-0003756
NOLA: IPR

would become

Local ID - IPTV Barcode: IPTVUS-0003756
Local ID - NOLA: IPR

**Comment by caseyedavis12** [comment]
Change the label for local identifiers (Local Station Identifier could be prepended to the Source value).

**Comment by sroosa** [comment]
Resolved a long time ago
