### ISSUE TITLE
Exact Search without stemming

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1157]
**Done when**

- [ ] In an advanced search for "This exact word or phrase," the search is on exact text that has no stemming or stop words taken out. It only matches if the characters match exactly.

**Comment by afred** [comment]
Setting to `Effort: high` because this requires a little more research to see if we need a separate field for descriptions, titles, etc, that aren't stemmed.

**Comment by foglabs** [comment]
Based on what I've read so far, it looks like this will require us to add non-stemmed copies of every field (<copyField... >) to the index, and not be doable via a blacklight setting.

**Comment by foglabs** [comment]
https://bibwild.wordpress.com/2011/06/20/customizing-blacklight-disable-automatic-stemming/

<field def without stemming>
https://gist.github.com/jrochkind/1029844

**Comment by afred** [comment]
I think we should...

**Comment by jasoncorum** [comment]
@afred - so we'd index each of our *_exact_match fields in a similar manner to how we're doing the *_titles here? https://github.com/WGBH/AAPB2/blob/master/app/models/pb_core.rb#L427

**Comment by afred** [comment]
@jasoncorum that line's a little confusing to me.. but... yes?

I was even thinking we could be pretty explicit about it in `#to_solr`... like...

```ruby
# app/models/pb_core.rb
def to_solr
  # ...
  'genres' => genres,
  'genres_exact_match' => genres
  # ...
end
```

I don't know if `genres` is a good example here or not.

@caseyedavis12 couple of questions...

1. Do we want the ability to "exactly match" any field? If not, which ones?

2. Does "exact match" mean an exact match of a subset of the full value? Or does it mean an exact match on the whole field value, and nothing but the value?

   1. For instance, if I search "conversation hillary clinton", I get the record titled "Voice of the Voter; Conversation with Hilary Clinton". Note the misspelling of "Hilary" in the title, and that my query lacked "with". If we do a strict "exact match" then I would have to both include the "with" in my query _and_ intentionally misspell her name.

**Comment by sroosa** [comment]
Resolved a while ago.
