### ISSUE TITLE
UX Team Discussion: Descriptions in Search Results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1158]
Only show certain amount of characters or something else so that 5 paragraphs don't appear. (Exact number of characters doesn't matter to me. We just want consistency in length and for the descriptions to not be super long. Maybe one-two sentences?)

Example of issue: http://americanarchive.org/catalog? f%5Baccess_types%5D%5B%5D=digitized&f%5Bmedia_type%5D%5B%5D=Moving+Image&f%5Borganization%5D%5B%5D=WGBH+%28MA%29&page=61&q=teachers+domain&utf8=%E2%9C%93

**Done when**
 - [ ] Implement a rule for selecting from multiple descriptions when mult desc are present.
 - [ ] Descriptions in search results only show up to a certain amount of characters.

**Comment by afred** [comment]
@caseyedavis12 or @sroosa Part of this issue is the fact that some records have multiple descriptions. Do we have a rule for which description (in the case of multiple) to use?

**Comment by sroosa** [comment]
@afred I think there is a rule already built in to the ingest or display logic that orders the transcripts. Let's just use the first xxx characters from the first description or up to the whole of the first description (if it's shorter than the limit), and not worry about any of the other descriptions in the serach results display. @caseyedavis12 : do you agree?

**Comment by caseyedavis12** [comment]
@sroosa: +1
