### ISSUE TITLE
Create functionality to display redacted proxy in ORR and original proxy on location

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1168]
For the NewsHour project, we will probably need to create functionality on the website to display the redacted proxy in the Online Reading Room and the original proxy for on location access.

We will know if this needs to be done by the end of February.

What should be the naming convention for the edited proxy that we post on Sony Ci?

**Comment by sroosa** [comment]
If we have 2 versions of proxy files for 1 GUID (one for On Location and one for ORR), then we will have to add an attribute to the Sony CI pbcoreIdentifier tags to identify which proxy is for which purpose.

**Comment by afred** [comment]
**NOTES DURING EFFORT ESTIMATION:**
  * we already have multiple Ci IDs for records with multi-part media
  * right now the default is to assume multiple Ci IDs are for records with multi-part media
  * adding additional flags for access level will multiply the conditions we have to take with Ci IDs
  * Unsure how to combine multi-part media with additional flags -- we only have two attributes on `<pbcoreIdentifer source="" ref="">`
    * possible to use pbcoreAnnotation? This would be cleaner re: data organization. But would essentially involve a sort-of "magic" annotation.
