### ISSUE TITLE
Implement new collections feature on AAPB website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1175]
Implement design recommendations for new AAPB Collections Feature

**waiting on:**
- [ ] Digital delivers comp specs for new Collections feature, including Homepage Section, Collections Landing Page, and Specific Collection page

**Done when**
- [ ] WGBH developers implement the Collections design
- [ ] Casey and Charles create American Masters pilot collection

**NOTE:** See Openvault on how collection membership is determined by metadata fields. This will be the same case for AAPB.

**Comment by sroosa** [comment]
replaced by #1627 and #1628
