### ISSUE TITLE
Allow vtt files to display as captions if no srts

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1183]
Updated:
Done when:
- [ ] if there is a srt file in the caption folder, it displays that
- [ ] if there is no srt file, but there is a vtt file, it displays that

**Comment by afred** [comment]
Questions:
  - [ ] How certain are we that Kaldi will be part of our workflow?

**Comment by caseyedavis12** [comment]
@afred: this is waiting a decision. We plan to test creating kaldi transcripts on the American Masters collection. The initial tests  will help us determine whether it is good enough to become part of our workflow.

**Comment by caseyedavis12** [comment]
@sroosa, I think this is the ticket for showing transcripts as captions.
