### ISSUE TITLE
NET Thumbnail appears for NET undigitized records

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1186]
Rather than the usual default "undigitized" thumbnail, NET undigitized records have a special default thumbnail.

**waiting on:**
  - [ ] special thumbnail
  - [ ] knowing which specific annotation to check

**Done when** the special thumbnail appears in the search results and on record pages for NET undigitized records.

**Comment by afred** [comment]
Question:
  - [ ] can we add a NET flag to the metadata to make the records more easily recognizable.

**Comment by sroosa** [comment]
@afred yes! we will be doing this. It will be some kind of annotation like the ones that tell you which organizations the records come from.
