### ISSUE TITLE
Pages on website very slow to load

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1201]
The pages on the website (including About pages) are very slow to load. For example, when I click on "About" from the homepage, it takes several seconds for the About page to load, and my spinner wheel does not spin, so there is no visual indication that clicking the link actually worked.

**Comment by caseyedavis12** [comment]
Have we checked the log roll in a while? Is our space filling up and causing the site to slow down?

**Comment by afred** [comment]
Hmm.. not slow for me using both Chrome and Safari, and after having cleared my cache. Can someone else confirm slowness? @jasoncorum @sroosa?

**Comment by jasoncorum** [comment]
I was just testing too. Cleared cache and not noticing any slowness @afred

**Comment by Muraszko-wgbh** [comment]
No slowness for me either.  Didn't clear my cache.  Still pretty quick on an older iPhone as well.

**Comment by caseyedavis12** [comment]
Sounds like it's just me. Closing.

**Comment by caseyedavis12** [comment]
Sorry all, I'm reopening this. I'm at home now and the site is really, really, really slow to load.

**Comment by afred** [comment]
Still not getting lags from where I am.

@caseyedavis12 have you experienced slowness on different machines? Or just your work laptop? Also.. do you have any specific links? Or is it the whole site?

**Comment by afred** [comment]
@caseyedavis12 this is 2 months old, and seems to be an intermittent problem. Without a way to reliably replicate it, we won't be able to solve it. Ok to close this?

That being said, we haven't put much effort into general website performance re: page load times. It may be something to focus on in the future if we keep have intermittent problems, yeah?
