### ISSUE TITLE
Configure to receive daily, demo notifications

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH-MLA/AAPB2#1213]
Get daily notifications when host named "demo.abc.wgbh-mla.org" is running.

**Comment by jasoncorum** [comment]
For reference: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/usage-reports-instance.html

**Comment by afred** [comment]
See https://aws.amazon.com/cloudwatch/details/#amazon-ec2-monitoring
