### ISSUE TITLE
Document deployment work flow

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#124]
**done when**
Deploying code from github is a followable, step-by-step process documented somewhere.

**Comment by afred** [comment]
I edited this ticket to be more actionable. Still need to make some discussion though. @mccalluc would love your input. Below are some bullet points related to OpsWorks. Could be pro or con, depending on how you look at them.

OpsWorks:
  - Seems to tightly couple the provisioning of VMs and deployment of code. But do we need the flexibility of keeping them separate?
  - Uses Chef, which I'm not opposed to learning, but its one more thing to learn.
  - Customization requires maintaining and hosting your own Chef recipes that OpsWorks can then pull in. This is ok by me, since I envisioned a similar system using Capistrano.
  - Introduces new AWS-specific architecture, "Stack", "Layers", "Apps", "Instances", which may be more complex than we need.
  - Allows for easier integration of other AWS services should we choose to use them, e.g. load balancers.
  - Have already sunk some cost into running through a deployment.
  - If we don't use it, we'll still need a way of provisioning VMs, since Capistrano isn't good for that.
  - Tightly coupled to AWS (obviously). If we were to change hosting services, we'd probably have to re-do the deployment workflow.

**Comment by afred** [comment]
evangelizers of OpsWorks:
http://viget.com/extend/aws-opsworks-lessons-learned
.. which links to..
http://artsy.github.io/blog/2013/08/27/introduction-to-aws-opsworks/

**Comment by mccalluc** [comment]
I would like to be more familiar with it, but it seems like its working so far. I think any particular system is going to have it's particulars: The ones here don't seem more onerous than the alternatives.

(Not advocating, but did you get to this at code4lib? Another kind of solution: http://code4lib.org/conference/2015/clarke)

**Comment by afred** [comment]
Yeah, that was a good presentation. I actually bumped into that guy on the train to the airport. He works for UCLA but lives in North Carolina. I've heard great things about Docker. Hadn't heard much about Packer.io yet though. Need to peel off and look at OV for a while. Come back to this later.
