### ISSUE TITLE
Implement Rights Statements in AAPB Metadata

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1256]
We would like to implement standardized Rights Statements within the RightsSummary field.

http://rightsstatements.org/page/1.0/?language=en

More information on specific licenses to use coming soon.

**Comment by caseyedavis12** [comment]
Done when

- [ ] New field appears on record pages that says "Rights Statement"
- [ ] Value of all fields says "In Copyright" with the rightsstatement.org icon for this statement
- [ ] If a user clicks on external link button next to "In Copyright" it takes the user to this page: http://rightsstatements.org/page/InC/1.0/?language=en

Here is a screenshot of what this looks like on the Europeana website:

![screen shot 2017-05-08 at 9 54 32 am](https://cloud.githubusercontent.com/assets/5992135/25807815/19bd653a-33d6-11e7-8a54-e02d4164253f.png)

You can download the In Copyright icon here: http://rightsstatements.org/en/documentation/assets.html (we just need the Icon, not the Button)

**Comment by caseyedavis12** [comment]
@sroosa: can you add this to the backlog.

**Comment by sroosa** [comment]
I need to work on this in the metadata and figure out mapping to standardized rights statements before we can proceed with this on the website.
