### ISSUE TITLE
Allows user to request logins for wiki.americanarchive.org

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1274]
@rfraimow can you add a done statement?

**Comment by jasoncorum** [comment]
@rfraimow - Is this what you were looking to add? https://www.mediawiki.org/wiki/Extension:ConfirmAccount

**Comment by rfraimow** [comment]
Yep, that's it! I think I'd like to keep the 50-word bio requirement, for the record. Let's let people know who's contributing.

**Comment by jasoncorum** [comment]
@afred & @sroosa - Thanks again for your input on this ticket. As we discussed, the Wikimedia version that came with the Turnkey solution is out of date (Mediawiki 1.19) and incompatible with this extension. I've done some research based on our discussions and I think the way forward will be to migrate the AAPB wiki to the Bitnami Mediawiki AWS solution (Mediawiki 1.26). Using their free local version, I've been able to both migrate the content and set up the ConfirmAccount extension.

Here's a link to AWS Marketplace page for Bitnami: https://aws.amazon.com/marketplace/pp/B0062ND1AK

I'm going to document the steps taken here for migrating content and setting up the ConfirmAccount extension. There might be a better way to migrate content (and users) that I can continue to look into, but at the very least we know that these worked on my local environment.

I think that this could all be done in about 1/2 a day once the AWS environment is set up.

**Content Migration**

1. Get a complete list of content at: http://wiki.americanarchive.org/index.php/Special:AllPages
2. Go to the UI for exporting pages: http://wiki.americanarchive.org/index.php/Special:Export
3. Enter the pages (one per line), include full history, incude templates, save as file and click Export. This will download an XML file.
4. On the new wiki, go to the Special:Import page: /mediawiki/Special:Import
5. Upload the file, this should migrate all the content and history in to the new wiki.

**ConfirmAccount Extension**

1. Follow the regular installation instructions: https://www.mediawiki.org/wiki/Extension:ConfirmAccount#Installation
2. Make sure '$wgEnableEmail = true' in LocalSettings.php
3. Add the following to the LocalSettings.php file for SMTP (Use our Amazon SES credentials for AmazonUser and AmazonPass): `$wgSMTP = array( 'host' => 'tls://email-smtp.us-east-1.amazonaws.com', 'IDHost' => 'email-smtp.us-east-1.amazonaws.com', 'port' => 465, 'username' => AmazonUser, 'password' => AmazonPass, 'auth' => true );'

**Comment by sroosa** [comment]
@jasoncorum great! I think that will be the way to move forward. Let me check in with Nick about switching the cost from the older version to the newer version and make sure that all still fits into the grant (just heard from Rebecca that if the cost can't be covered by the grant, then it might not be worth doing, with the understanding that they then wouldn't be able to use the confirm accounts extension.
