### ISSUE TITLE
Add Transcript API Credentials to AAPB Deployment

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#1288]
The transcript API requires a username and password that are defined as environment variables, API_USER and API_PASSWORD respectively. 

Done when:
- [x] API_USER and API_PASSWORD are defined environment variables

**Comment by jasoncorum** [comment]
@afred - I submitted a PR on the Stash repo for aapb_deployment.

**Comment by sroosa** [comment]
@jasoncorum did this get merged on Stash? can we close this ticket?

**Comment by jasoncorum** [comment]
@sroosa - hasn't been merged yet. @afred could you take a look at my PR on stash for this? thanks!
