### ISSUE TITLE
Develop workflow for updating transcripts

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1291]
Done when:

- [ ] There is a documented workflow to use manifest from #1178 to update metadata records, including attribute on display 
- [ ] There is documentation on overwriting older transcripts with corrected transcripts on S3 (possibly using @jasoncorum's to-aws script)
- [ ] Reindexed records display the corrected transcript

**Comment by ekemeyer** [comment]
Done
