### ISSUE TITLE
Better internal navigation

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1322]
I think we should have better internal navigation on the website. This is accomplished well on our exhibits pages, where at the top it shows the parent page of the exhibit. 

<img width="699" alt="screen shot 2017-07-19 at 9 25 19 am" src="https://user-images.githubusercontent.com/5992135/28368988-3234f8fa-6c64-11e7-95a2-cafb0e3c2235.png">

Can this also be done on our Participating Organizations pages and Projects Pages?

This may be a different fix, but on record pages, if someone has conducted a search, can we have a button that says go back to your search results?

Done when: 
On the Participating Organizations page, add the breadcrumb that takes the user back to the page that lists all Participating Organizations. Use the same design as Exhibits breadcrumbs.

If a user conducted a search and then clicked to a record page, provide a link above the player/thumbnail that says "Back to Search Results"

**Comment by caseyedavis12** [comment]
On Digital Commonwealth, a user can conduct a search, click on a record, and there is a button that will take the user back to their search results: https://www.digitalcommonwealth.org/search/commonwealth:5h73tn126

**Comment by caseyedavis12** [comment]
@sroosa: are you waiting on me for a done when statement?

**Comment by sroosa** [comment]
@caseyedavis12 yes, I guess so. We just didn't know what this would actually look like. Did you want us to explore options, or did you already know what you wanted it to look like and we just need to implement it?

**Comment by caseyedavis12** [comment]
On the Participating Organizations page, add the breadcrumb that takes the user back to the page that lists all Participating Organizations. Use the same design as Exhibits breadcrumbs.

If a user conducted a search and then clicked to a record page, provide a link above the player/thumbnail that says "Back to Search Results"

**Comment by jasoncorum** [comment]
@sroosa - not exactly sure which pages this this means by for "Participating Organizations page" so URL would be helpful.
