### ISSUE TITLE
Refactor LinkChecker

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#1332]
The LinkChecker class used in our testing infrastructure could use a refactor because it returns more false positives than actual broken links. 

Done When
- [ ] We log potential broken links to a file, but don't raise an error.
- [ ] Run via a cron job (weekly?) and email results to developers for confirmation of broken links.

**Comment by afred** [comment]
worth noting that there are services that do this as well. Might be worth spending an hour or two doing research. Advantages would be...

1. likely fewer false negatives
1. possibly could use the service for all of our sites, without having to port link checker to everything, which is simpler.
1. eliminating the link checker reduces codebase complexity.
1. might not require any kind of cron job, which would be simpler still
