### ISSUE TITLE
Update "Transcript Not Available" Display

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1338]
Add some copy like "A speech-to-text transcript has been created for this item, but it is in the process of being corrected. Play our FIX IT game to help us correct our transcripts" and possibly use the FIX IT logo.

Done when:

- [ ] mock up of new display is approved
- [ ] approved mock up is implemented

**Comment by caseyedavis12** [comment]
@sroosa: We can put this on hold until we figure out what we're doing with the NYPL tool.

**Comment by sroosa** [comment]
@caseyedavis12 Yep! It's not in the prioritized to-do list yet, so I'll just leave it here in the backlog until we have everything else planned out.
