### ISSUE TITLE
Spin up a test instance of AAPB for transcript testing

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1341]
In addition to our normal production and demo sites, we need another site that runs the same as the current AAPB demo, but without any of the transcripts appearing or even indexed in solr. 

Usability students at Simmons will be using this site to test searching the website without the transcripts, while another group tests searching with the transcripts.

**Comment by jasoncorum** [comment]
@sroosa - here's the instance. actually have more records than production for now. http://54.156.140.91/catalog?q=&utf8=%E2%9C%93&f[access_types][]=digitized. if this looks good, let's turn off the instance and close the ticket.

**Comment by sroosa** [comment]
@jasoncorum This looks good. Is this the same IP address you sent @caseyedavis12  before? Yeah, we can go ahead and close the ticket. Then we'll be able to run our own tests on this version of the site versus the version with the transcripts indexed. And Casey can pass the link onto the Simmons UX class.

**Comment by jasoncorum** [comment]
@sroosa - it's not the same ip since the instance was stopped at some point. since that is the case, i'd say we stop the instance again and provide the new ip when they need it. thoughts?

**Comment by sroosa** [comment]
@jasoncorum just confirmed with Casey. We're fine to stop the instance for now. I'll let you know when we need the new ip address for testing.
