### ISSUE TITLE
Clicking from "All Digitized" to "Available Online"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1342]
I am viewing search results in the "All Digitized" filter and am on page 3 of 7 in the search results. I decide to click to "Available Online" because there are two assets that are available online. When I click "Available Online" filter, the search results page is blank because I was several pages deep in the previous "All Digitized" search results, and the search results does not refresh to page one of search results.

Example: 
Click "Available Online" on this page:
http://americanarchive.org/catalog?f%5Baccess_types%5D%5B%5D=digitized&f%5Borganization%5D%5B%5D=KUCB+%28AK%29&page=3&q=

- [ ] **Done when:** search results refreshes to Page 1 of search results when you click on a different Access facet.

**Comment by foglabs** [comment]
Added a conditional that sends search back to page 1 when there would be less than 1 search result on the current page.

Screens:


![screen shot 2019-01-14 at 1 32 35 pm](https://user-images.githubusercontent.com/8140840/51132948-a1cb4d00-1801-11e9-8f7e-0da62754732a.png)
![screen shot 2019-01-14 at 1 32 43 pm](https://user-images.githubusercontent.com/8140840/51132954-a4c63d80-1801-11e9-9941-fb7b244a7922.png)
![screen shot 2019-01-14 at 1 32 54 pm](https://user-images.githubusercontent.com/8140840/51132958-a7289780-1801-11e9-9fb6-82f8c7728fdb.png)
