### ISSUE TITLE
Rethink participating organization pages

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1347]
We want to change the headers of this at least (switch History to About, and maybe just move Productions into that section too, or remove it entirely). Before we start work on it, let's make a final decision about what we want to page to include and look like.

Done when we have a list of what we want to the page and a mock up of the layout.

**Comment by caseyedavis12** [comment]
Definitely get rid of Productions section altogether.


Change History to About


Can we just remove the side menu and widen and center the right column?
