### ISSUE TITLE
Add record-specific links out to FIX IT+

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1467]
## Description 
We would like to add a button on the record page to show users that there is a transcript for this media that they can help correct in FIX IT+. There should be text around it like "The machine-generated transcript for this records needs to be corrected." And then the button can say something like [Correct Transcript].

## Done Looks Like 
- [x] Design for button and any messaging around it is approved by PM
- [ ] When Transcript Status = "Correcting" the button appears
- [ ] When a record has it's Transcript Status updated to "Correct" and the record is reindex on AAPB, the user no longer sees the button on the record page. 
- [ ] When a user clicks the button, a new tab opens on the page for that same GUID in FIX IT+.

**Comment by foglabs** [comment]
Took a quick crack at this:

![screen shot 2018-10-18 at 9 40 27 am](https://user-images.githubusercontent.com/8140840/47159087-0fc3af00-d2bb-11e8-9a98-3386c4211fcf.png)

**Comment by caseyedavis12** [comment]
@foglabs and @sroosa, can you edit the text to say “Want to help make this content more accessible? Correct our machine-generated transcript.”

**Comment by foglabs** [comment]
Changed!

**Comment by sroosa** [comment]
Resolved a long time ago
