### ISSUE TITLE
Update Transcript Viewer display logic

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1499]
## Descriptions of changes:
New Transcript Status annotation values:
Uncorrected
Correcting
Correct
 
Logic we would like:
Transcript Status = "Uncorrected" or "Correcting" and Level of User Access = "Online Reading Room"
The transcript should be viewable in the transcript viewer, but the viewer should default to closed. When the transcript viewer is opened it should have a message that says:
"This transcript is machine-generated and has not been corrected. It is likely there will be errors." 

Transcript Status = "Correct" and Level of User Access = "On Location" 
The transcript, like the media, should only be viewed when IP address ranges are for WGBH or Library of Congress. The transcript viewer should default to open and should not include the message described above.

Transcript Status = "Correct" and Level of User Access = "Online Reading Room"
The transcript, like the media, should be viewable to the public. The transcript viewer should default to open and should not include the message described above.

Transcript Status = "Correct" and there is no Level of User Access 
(this would be something we have a transcript for, but don't have media for). 
The transcript should be viewable to the public. The transcript viewer should default to open and should not include the message described above.

## Done Looks Like:
- [ ] Logic described above functions
- [ ] Design for the "This transcript is machine-generated and has not been corrected. It is likely there will be errors."  message is approved by PM.

**Comment by foglabs** [comment]
![screen shot 2018-10-18 at 9 38 42 am](https://user-images.githubusercontent.com/8140840/47158924-b3608f80-d2ba-11e8-8f09-e5a147ba91db.png)

**Comment by caseyedavis12** [comment]
@sroosa can the FIX IT+ button be right next to this statement?

**Comment by sroosa** [comment]
@caseyedavis12 it can be; however, we originally said we wanted the FIX IT+ button on the page even when the transcript viewer was closed, since that's how it will default. What do you think now?

**Comment by caseyedavis12** [comment]
@sroosa, yes let’s go with the original plan. Can I see a screenshot of what it will look like when that’s done?
