### ISSUE TITLE
Change FIX IT logo in header to T2D logo

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1609]
Change FIX IT logo in header to T2D logo, and link to FIX IT+

Awaiting LOC approval.
<img width="936" alt="td_bug" src="https://user-images.githubusercontent.com/5992135/48263896-a1739780-e3f5-11e8-9af7-413794bf2db9.png">

**Comment by caseyedavis12** [comment]
@sroosa this is approved! Can we make the fix for the next redeploy?

**Comment by foglabs** [comment]
Including in pull #1651
