### ISSUE TITLE
Add VTT-to-HTML Conversion for caption snippets in search results, when caption file source is VTT

### ISSUE THREAD

**Issue by foglabs** [WGBH-MLA/AAPB2#1610]
As part of #1603, we now allow caption files (on S3) to be stored in VTT or SRT format.

The caption-snippets-in-your-search-results feature ( #1593 ) converts the caption data from srt to html for the view, but can't do this for a vtt source file.

Finished when:
-CaptionFile can convert captions from vtt to html
-we handle this distinction correctly in snippet_from_query caption code

**Comment by singlesoliloquy** [comment]
Duplicate ticket https://app.zenhub.com/workspaces/mla-developers-5d0a8ef27c5752598acebdb1/issues/wgbh-mla/aapb2/2232
