### ISSUE TITLE
SSL Certificate Set Up for New Elastic IP

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#1640]
According to AWS documentation, certificates need to be associated with an Elastic Load Balancer or Cloudfront distribution. The certificate was initially set up to work with our old ELB setup but doesn't seem to work with the new Elastic IP. 

- [ ] Done when the site can be served via SSL again.

**Comment by jasoncorum** [comment]
Useful AWS documentation link: https://docs.aws.amazon.com/acm/latest/userguide/acm-services.html

**Comment by sroosa** [comment]
resolved
