### ISSUE TITLE
Sort by Episode Number

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1653]
If a Found Set includes ```<pbcoreTitle titleType="Episode Number">``` allow sorting by Episode Number

**Comment by jasoncorum** [comment]
@sroosa - i just wanted to flag that we will probably need to index this as a separate field from the titles (though we can keep it there too) which would probably require a complete re-index. does that sound ok?

**Comment by sroosa** [comment]
Yep! That is totally fine @jasoncorum
