### ISSUE TITLE
On Firefox, Weird Back Button Behavior

### ISSUE THREAD

**Issue by foglabs** [WGBH-MLA/AAPB2#1681]
Ryn noticed some strange behavior when navigating around search results *on firefox*:

-Sometimes hitting back button from a record page appears to just reload the same record -> hitting refresh will subsequently load the correct previous page. This may be some kind of weird turbolinks restoration behavior.

-Sometimes (after navigating between multiple records), hitting the back button will go back two steps instead of one. The page that appears is actually navigated to, unlike the third example (refresh maintains the apparent page).

This is going to need some more exacting investigation, but creating this now... for later.

**Comment by sroosa** [comment]
Resolved when we got rid of turbolinks
