### ISSUE TITLE
Double Player On Particular Record

### ISSUE THREAD

**Issue by foglabs** [WGBH-MLA/AAPB2#1682]
http://americanarchive.org/catalog/cpb-aacip_309-52w3r6m6

This record causes two player instances to appear, with the same content. Looks like there are two ci_ids in the pbcore, causing two players to be added to the page.

**Comment by sroosa** [comment]
Not an issue with the page, but rather with the way we handle multiple files attached to one record. So not an issue that needs to be resolved per this ticket.
