### ISSUE TITLE
BUG - Error controller showing 500 when in 404 situation

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#1686]
**Expected behavior:** When you go to /foo, or /foo.bar, or /foo.gif, or anything else, you should get a 404.

**Actual behavior:**
  1. If you go to /foo, /foo/bar, /foo.bar, or /foo.html, you'll an HTML rendering of a 500 page, with 500 status code.
  2. if you go to /foo.gif, /foo.jpg, /foo.xml, /foo.json, you'll get an unstyled exception:
      ```
       500 Internal Server Error
       If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
      ```
      This also drops an error in `/var/log/httpd/error_log` with a full stack trace, which fills the log up rapidly.

It's very important that 404's get handled correctly, without bloating any logs, or other nasty side effects.

**Comment by foglabs-zen** [comment]
this issue should be taken care of by AAPB pull https://github.com/WGBH-MLA/AAPB2/pull/1946

**Comment by afred** [comment]
close in favor of #806
