### ISSUE TITLE
BUG - Fix S3 mount for Rails log

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#1687]

**Comment by afred** [comment]
**Background:** We were getting errors on production for inability to write to `aapb-remote-storage/log/production.log`. At first, this was bloating the Apache logs, but the website was still running. Then after restarting apache, it was causing Rails to fail to start.

When you looked inside of teh `aapb-remote-storage` directory, there were several timestamp-named directories, each containing several rotated `production.log` files.

In `config/environments/production.rb`, the log is specified to write to `aapb-remote-storage/log/production.log`. So I'm not sure what is creating the timestamp-named directories, and how the log is actually getting written into there.

**Comment by sroosa** [comment]
No longer using S3 mount
