### ISSUE TITLE
Update year facet to work with more granular dates

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1716]
Much like in AMS2, we would like AAPB to be able to get dates that are any of the following 
YYYY, YYYY-MM, or YYYY-MM-DD. Then people should be able to search for an exact date (in any of those formats) or a range (with any of those formats as the start and end dates).

**Comment by foglabs** [comment]
-'sort by year' gives correctly ordered records as listed above
-facet by an exact date OR a range of dates, using the above handling

**Comment by sroosa** [comment]
Moved part of this ticket to #1652

**Comment by sroosa** [comment]
Closed by #1799
