### ISSUE TITLE
Figure out zero-downtime staging / redeploy

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/AAPB2#176]
So opsworks redeploys work pretty well, but some things worry me:
- The jetty/solr is under one particular checkout, and after 5 redeploys, it will be deleted.
- Sometimes things are different in production. Right now, we wouldn't see it until it got deployed.
- Rails warm up on start. Not horrible, but still.

Read this: http://www.thoughtworks.com/insights/blog/implementing-blue-green-deployments-aws
- Sign up for an AWS Elastic IP
- Get a fresh EC2 instance with the latest code.
- If there haven't been changes, make an image of the solr index, and load it into a new EBS
- Hook the EBS to the EC2, start jetty, etc.
- Make sure the new server is happy
- Switch the Elastic IP
- Keep the old one around till ...? Is having a script reap old ones more or less scary than killing them by hand?

**Comment by caseyedavis12** [comment]
@afred is this done?
