### ISSUE TITLE
gather list of specs that have convoluted looping

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1776]

**Comment by jasoncorum** [comment]
models/exhibit_spec.rb
models/pbcore_spec.rb
models/special_collection_spec.rb
features/catalog_spec.rb

**Comment by jasoncorum** [comment]
catalog_spec.rb loops are xit-ed out and should be removed soon. download_clean_ingest.rb process is slated for refactor, so leaving that spec as is as well.
