### ISSUE TITLE
Allow page titles to be American Archive of Public Broadcasting

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1868]
Casey's change in #1826 is failing some test that it preventing us from having pages just called American Archive of Public Broadcast. EXCEPT we actually do want this page to be called that: it's the name of the grant that the page describes. To me, it seems like we don't need this test at all. I'd be fine with scrapping it. 

Done when:
- [x] #1826 passes

**Comment by foglabs-zen** [comment]
This was completed when the `expect_fuzzy_xml` file - `validation_helper.rb` - was deleted. Just needed to merge and re-run the build.

**Comment by sroosa** [comment]
Closed in #1826
