### ISSUE TITLE
Accordion metadata sections don't open on mobile

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1884]
The accordions wit the Credits, AAPB Contributor Holdings, and Citations metadata don't open on record pages viewed on iPhones (at least).

**Comment by afred** [comment]
Could not replicate using Safari and Chrome emulators for iPhone.

Is there a specific device / OS combination that's having problems?

**Comment by foglabs-zen** [comment]
works on firefox and chrome on android
