### ISSUE TITLE
Update Embed to Share with direct link and embed code

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1885]
Update button to say Share. (While we're there, update all three buttons (skip back, skip forward, and share) to be longer, so all text fits on one line).

Update pop down into a modal. Modal has option to share from beginning or at current time code, and both a "Share" link  that is juust to the record page (possibly with timecode) and "Embed" code that has the embed link and the iframe, like it currently does.

**Comment by jasoncorum** [comment]
@sroosa - could you take a look at these screen shots and let me know if you'd like any changes? thanks!

![Screen Shot 2019-11-08 at 8.00.18 AM.png](https://images.zenhubusercontent.com/5d2cad171325bafe06490b12/41945410-a026-416e-93e8-5815ca19fe90)
![Screen Shot 2019-11-08 at 8.00.36 AM.png](https://images.zenhubusercontent.com/5d2cad171325bafe06490b12/9c674188-7ac6-4597-a418-707e2836cbce)
![Screen Shot 2019-11-08 at 8.00.43 AM.png](https://images.zenhubusercontent.com/5d2cad171325bafe06490b12/353b530b-dbdf-4f64-a7a5-666e2c4092d0)

**Comment by sroosa** [comment]
@jasoncorum can you have it show both the Share and Embed at the same time. Maybe the Share on top with a copy box that has the link, and then the Embed beneath that has the larger copy box. I just think if they already has to click a button to open the modal, I'd rather they didn't have to click another button right away.

**Comment by jasoncorum** [comment]
Revised screenshot approved by @sroosa via Slack.

![Screen Shot 2019-11-08 at 11.20.45 AM.png](https://images.zenhubusercontent.com/5d2cad171325bafe06490b12/79adf3e4-17ee-4619-992d-929d6a377ef1)
