### ISSUE TITLE
XML view doesn't include xmlns

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1896]
XML shown by adding .pbcore to a record page is not validating. It seems like the only invalid part is in the declaration. Right now it includes schema location, like:

`<pbcoreDescriptionDocument xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html http://www.pbcore.org/xsd/pbcore-2.0.xsd">`

But it does not include the namespace declaration. So we need to update that view to look like:

<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespac.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html https://pbcore.org/xsd/pbcore-2.0.xsd">

**Comment by foglabs-zen** [comment]
Seems to be coming through correctly now:

```
<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html http://www.pbcore.org/xsd/pbcore-2.0.xsd">
<pbcoreAssetType>Episode</pbcoreAssetType>
...
```

**Comment by sroosa** [comment]
We have determined that this is an issue with Firefox's printing of the XML. It has not been an issue on Chrome at all. So we now that we know that, we can direct people who want their XML example to be valid to Chrome, and still let Firefox users see the XML that has all of the data, but just isn't technically valid because of the missing namespace attributes.
