### ISSUE TITLE
Replace calls to `unescape_path` with something else

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#1899]
### Because

Dependabot PR #1894 is failing with a bunch of these errors:
```
NoMethodError:
       undefined method `unescape_path' for Rack::Utils:Module
```

### Done when
* We replace calls to `unescape_path` with whatever else works.
* Tests pass for #1894

**Comment by foglabs-zen** [comment]
were these calls inside a gem? searching now, I don't find any instances of this method being called in AAPB. if they are inside a gem, maybe we should solve this problem with further upgrades to that gem?

**Comment by afred** [comment]
I don't know where the calls are being made. I'm going to try rebasing and see if that helps with anything (probably not, but will resolve the Gemfile.lock conflicts in any event). Stand by.

**Comment by foglabs-zen** [comment]
merged Drew's rack upgrade PR, should be all set.
