### ISSUE TITLE
Add bad-bots.conf to AAPB deployment

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#1908]
**NOTE:** This will probably end up as a PR in [aapb_deployment repo](https://atlas.wgbh.org/stash/projects/MLA/repos/aapb_deployment/browse) (need to be logged into VPN to access this repo).

### Because

Our wee web server was overwhelmed by a bot, presumably from China. We had to put some directives in the Apache config to deny requests (responding with a 403 Forbidden) that contained any number of blacklisted keywords in the User-Agent header field.

### Done when

Deploying AAPB includes ensuring that a file at `/etc/httpd/conf.d/bad-bots.conf` contains the following Apache config...
```
<Location />
  # Deny requests with any of the following strings in the User-Agent header.
  BrowserMatchNoCase "LieBaoFast" bad_bot
  BrowserMatchNoCase "Mb2345Browser" bad_bot
  BrowserMatchNoCase "zh-CN" bad_bot
  BrowserMatchNoCase "MicroMessenger" bad_bot
  BrowserMatchNoCase "zh_CN" bad_bot
  BrowserMatchNoCase "Kinza" bad_bot
  BrowserMatchNoCase "Bytespider" bad_bot
  BrowserMatchNoCase "Baiduspider" bad_bot
  BrowserMatchNoCase "Sogou" bad_bot
  BrowserMatchNoCase "undefined" bad_bot
  Deny from env=bad_bot
</Location>
```

**Comment by sroosa** [comment]
Done in WGBH private bit bucket
