### ISSUE TITLE
Explain to users better how Share at current time works 

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1918]
Share at current time links (like https://americanarchive.org/catalog/cpb-aacip_15-hd7np1wp4c#at_520.892586_s) don't work in Safari. There might be other particularities that we know, but which users won't know about right away. It would be good to have some messaging about that for users trying to use the feature. 

@caseyedavis12 what do you think about this? And what do you think this should look like?

**Comment by foglabs-zen** [comment]
Test right now indicates that sharing now works in safari

**Comment by foglabs-zen** [comment]
also, 'share at current time' will likely soon be replaced by in/out slider feature.

**Comment by jasoncorum** [comment]
Closed due to Slider!
