### ISSUE TITLE
Outline what underlying gems are getting very out of date and what migration looks like

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1926]
### Because
We need to plan for AAPB future upgrades.

### Done when
  1. Current state of key components, Blacklight, et al
  1. Meeting scheduled.

**Comment by afred** [comment]
* Rails - Current: 4.2.8; Latest: 6.0.2.1
* Blacklight - Current: 5.19.2; Latest: 7.5.1

**Comment by afred** [comment]
Agenda for meeting: https://gist.github.com/afred/4d5af594da661e27e856f705e286c0d8
