### ISSUE TITLE
Create Special Collection-specific facets

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#1947]
As a user, I should be able to go to a special collection page and browse the collection by topics/genres specific to that collection. These can take the form of buttons that appear below the search box.

**Comment by sroosa** [comment]
We kind of have this already with the Terms section of the markdown, where someone writing a special collection can include terms they want to appear as button that will do a keyword search for those terms. I think that feature (which I don't believe any special collection is currently utilizing) can be built out to allow for this too.

**Comment by jasoncorum** [comment]
Expect something like this in the XML.
`<pbcoreAnnotation type=“Special Collection Category”>Sermon</pbcoreAnnotation>`
