### ISSUE TITLE
Bug: cannot use AAPB embed code in Wordpress

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/AAPB2#1948]
### Replicate
1. On AAPB Wordpress site, try to use AAPB embed code in a page.
1. It does not show up when you look at a draft of the page, nor when you publish it.

### Done when
1. AAPB embed code works on Wordpress... OR...
1. We have a clear understanding of why it does not work, and have a plan to deal with it.

**Comment by afred** [comment]
**WAITING:** for @caseyedavis12 to report back on whether we will upgrade to "professional" version, which is required in order to install plugins, and we need the "iframe" plugin to post `<iframe>` from AAPB.

**Comment by singlesoliloquy** [comment]
I've embedded on wordpress sites.
