### ISSUE TITLE
Items with annotation type "canonical meta tag" should have HTML canonical meta tags created upon ingest

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2006]
As a user, when I ingest items from AMS2 with an annotation type "canonical meta tag," the HTML page for that item should have a canonical meta tag in the header using the URL included in the annotation so that the item points back to the item of record.

Done When: the canonical meta tag is present in the HTML and corresponds with the PB Core metadata.

[Dependent on ticket #442 in AMS](https://app.zenhub.com/workspaces/mla-developers-5d0a8ef27c5752598acebdb1/issues/wgbh-mla/ams/442).

**Comment by singlesoliloquy** [comment]
[https://app.zenhub.com/files/26285120/5f225462-d90c-436d-8a66-c93fbeea5543/download](https://app.zenhub.com/files/26285120/5f225462-d90c-436d-8a66-c93fbeea5543/download)

**Comment by singlesoliloquy** [comment]
As a user, when I ingest a record that has "canonical meta tag" as an annotation
type it should create an html canonical meta tag and add it to the header so that
it points back to the url of record.

Done When: The correct canonical meta tag is added to the html from pbcore upon ingest.

**Comment by jasoncorum** [comment]
I think we already have something in place for this? Let's look at this PR:

https://github.com/WGBH-MLA/AAPB2/pull/1895/files
