### ISSUE TITLE
Create static section called "Primary Source Sets"

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2007]
This will look similar to the exhibits page.

**Comment by foglabs-zen** [comment]
is this ready to do, or pending alan input?

**Comment by singlesoliloquy** [comment]
I'll check this morning and get back to you.

**Comment by singlesoliloquy** [comment]
We will be holding off on this for a while.

**Comment by foglabs-zen** [comment]
ok, thanks!
