### ISSUE TITLE
Add Riverside (WRVR) transcripts their fixit+

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2019]
## Done When
New transcripts have been added to WRVR fixit+ after being pushed to AAPB http://wrvrtranscripts.americanarchive.org/.

**Comment by jasoncorum** [comment]
Since we released the fix for GUIDs I pinged Miranda about running the 'Push to AAPB' functionality on AMS2 to see if that's working as expected. If so, we can run the ingest on the WRVR Fix It instance.

**Comment by singlesoliloquy** [comment]
Does @foglabs-zen need to help on this? Or help with the blocker?

**Comment by jasoncorum** [comment]
Now blocked by https://app.zenhub.com/workspaces/mla-developers-5d0a8ef27c5752598acebdb1/issues/wgbh-mla/ams/442
