### ISSUE TITLE
Captions Not Appearing On AAPB Player

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2023]

**Comment by foglabs-zen** [comment]
-`captions_src` method referred to xml for caption url annotation
-captions src was generated on ingest
-a bug was introduced that expected the constructed-on-ingest caption url annotation to be present, when it could never be
=> subsequent ingests deleted caption url annotation, making aapb not look up the captions

fixed when `CaptionFile` takes guid instead of url, and uses guid to determine caption existence via http

we also discussed adding s3api initializer that checks for all caption files on server boot and stores in some kind of state local to the server, as indicator of caption existence

**Comment by jasoncorum** [comment]
This ticket was laying around, but I found the PR for it so going to move to "On Production".
https://github.com/WGBH-MLA/AAPB2/pull/2026
