### ISSUE TITLE
Look into displaying runtime on video playback

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#2031]
### Because

 Currently, the player is only showing the time remaining as a negative number

![image](https://user-images.githubusercontent.com/1507490/82239331-9b257c00-9906-11ea-8590-bee0093525d5.png)

### Done when
1. Explore the possiblility of showing current running time of the video playback (as an increasing number from the beginning).
1. If it's possible, then implemented.

**Comment by singlesoliloquy** [comment]
Ready for production.
