### ISSUE TITLE
Validate GUID Format on Ingest

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/AAPB2#2037]
As a lot of our functionality relies on 'cpb-aacip' guids, we should should update the ingester to validate that guids coming in are in an expected format. 

- [ ] Done When the PBCore ingest process validates guid format for ingesting in to the AAPB

**Comment by singlesoliloquy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MLA-Developers-5d0a8ef27c5752598acebdb1/issues/WGBH-MLA/AAPB2/2037?planning-poker) with ZenHub @afred @jasoncorum
