### ISSUE TITLE
Exhibit Gallery malforms outside 'media-url' elements

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2056]
Because:
We want to store a video url as a  `<a class="media-url"><URL></a>` element in an Exhibit Gallery Item, but the markdown parser will turn a real outside url (https://s3..blahblah) into yet another link element, inside the `<a class="media-url">` element, making the media url inacessible.

Done when:
Exhibit gallery looks for 'media-url' in the href property of <a class='media-url'> element, instead of element text.

**Comment by singlesoliloquy** [comment]
Ready for production
