### ISSUE TITLE
Add one transcript to FIXIT+

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2074]
## Done When

This one transcript needs to be added to FIXIT+ https://americanarchive.org/catalog/cpb-aacip_60-386hdxh3. The person interviewed reached out to Ryn and wants to correct it.

**Comment by jasoncorum** [comment]
Added
http://fixitplus.americanarchive.org/transcripts/cpb-aacip_60-386hdxh3
