### ISSUE TITLE
US Virgin Islands Is Geoblocked

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2076]
People are having trouble accessing AAPB in the USVI, per the attached email chain. The person emails back to say that they *can* access videos on their phone, but we would like to fix this for anyone else in the USVI. See if we have the ability to fix this given MaxMindDB geoblocking's limitations.

Henry-

Update from the patron:
"Hi Samantha,
Thank you for your message. It appears that the issue only happens when I use WiFi, but not if I use cellular data. So I’ll be fine for now. It was many videos so I wouldn’t want to take my time and yours for each individual video. I’ll just keep using my cellphone data. Thank you! 

Best regards,
Roxanne 
Sent from my iPhone"

From: Samantha Driscoll <samantha_driscoll@wgbh.org>
Sent: Friday, June 5, 2020 11:50 AM
To: Henry Neels <henry_neels@wgbh.org>
Subject: AAPB geo-block USVI Fw: Error Message
 
Hi Henry,

Ryn told me to forward this to you to investigate. Content in the AAPB is geo-blocked in the US Virgin Islands. Can you and the developers look into this?

Thanks!
Sammy

Samantha May Driscoll (she/her/hers)
Archivist | WGBH Media Library & Archives
One Guest Street​
Boston, MA 02135
617-300-4339
From: AAPB Notifications <aapb_notifications@wgbh.org>
Sent: Friday, June 5, 2020 9:45 AM
To: Samantha Driscoll <samantha_driscoll@wgbh.org>
Subject: Fw: Error Message
 

From: Roxanne Alina <ra@roxannealina.com>
Sent: Thursday, June 4, 2020 2:32 PM
To: AAPB Notifications <aapb_notifications@wgbh.org>
Subject: Error Message
 
Hi,
I’m in the USVI and when accessing numerous videos on your site I am seeing a message that the country that I am in doesn’t allow the playback of the video. Could you please help me?

Thank you. 

Sent from my iPhone

**Comment by singlesoliloquy** [comment]
Priority

**Comment by singlesoliloquy** [comment]
We have it whitelisted. Nothing else we can do. @samanthamaydriscoll
