### ISSUE TITLE
Missing "share a segment" from record

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2120]
## Issue
Why is "share a segment" missing from this record: [https://americanarchive.org/catalog/cpb-aacip_375-19s1rs0s](https://americanarchive.org/catalog/cpb-aacip_375-19s1rs0s)?

## Done When
"Share a Segment" functionality is added or there's a such a good reason for it not being there we all pause and say, "oh yeah, that makes sense."

**Comment by singlesoliloquy** [comment]
Hey @foglabs, Miranda fixed the duration. Does it need a MediaInfo bag too?

**Comment by foglabs-zen** [comment]
@singlesoliloquy - the duration value is the only needed for the segment tool
