### ISSUE TITLE
Update Arkansas Public Television landing page

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2169]
## Done When

Logo and summary are updated.

## Summary

Arkansas PBS is Arkansas’s only statewide public media network, which enhances lives by providing lifelong learning opportunities for people from all walks of life. Arkansas PBS delivers daily, essential, local, award-winning productions and classic, trusted PBS programs aimed at sharing Arkansas and the world with viewers through multiple digital platforms, including on-demand services and YouTube TV, and the distinct channels Arkansas PBS, Arkansas PBS Create, Arkansas PBS KIDS, Arkansas PBS WORLD and Arkansas PBS AIRS on SAP. Learn more at myarkansaspbs.org.

![ArkansasPBS_Logo_RGB.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/d2e44f51-d1b4-480c-97d5-42c21ee6ddb1)

**Comment by jasoncorum** [comment]
Since this is a name change we're going to have to reindex all their records when we change the name. I'm going to split this in to a separate PR from the other orgs that I'm updating due to this.

**Comment by singlesoliloquy** [comment]
Just update summary and logo. Ryn or I will contact them and tell them we can't change org name right now.

**Comment by singlesoliloquy** [comment]
@jasoncorum just update logo and summary
