### ISSUE TITLE
NET Conservatism Exhibit Sort

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2198]
## User Story
As a user, the NET and Modern Conservatism exhibit sort of programs would be easier to navigate by date ascending. Right now, the default sort is by relevance, which makes no sense, since all the programs are about the topic. Sorting by date ascending would put them into an order that would allow people to see shifts according to date.

## Additional Information

Low priority

## Done Looks Like

View all records in Conservatism Exhibit sorts records by date ascending.

**Comment by singlesoliloquy** [comment]
Sorted by date ascending, though it does say "relevance." [https://americanarchive.org/catalog?f%5Bexhibits%5D%5B%5D=conservatism&sort=year+asc&f[access_types][]=online](https://americanarchive.org/catalog?f%5Bexhibits%5D%5B%5D=conservatism&sort=year+asc&f[access_types][]=online)
