### ISSUE TITLE
SCCtv records not showing up in SCCtv org on AAPB

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2203]
Because:
Miranda reported that SCCtv's records were not showing up when clicking through their org page:
https://americanarchive.org/participating-orgs/NCSG55118

The instantiationAnnotation type="organization that links an AMS2 record to an AAPB organization IS present in the input xml and in AAPB

The root cause of the problem is that AAPB does not use the 'short name' markdown field to link a record to an Organization, it actually uses the 'title' field at the top of the organization markdown file.

This confusion was likely caused by the fact that in almost every case, the 'title' and 'short name' fields are identical in AAPB. The 'title' field values are slightly more verbose.

Done When:
We reconcile this discrepancy and choose to use one field, consistently, to link orgs and their records. This should *probably* be the short name field, because that seems to be the current practice, but we will have to make sure that switching to 'short name' will not mess up existing orgs that work *now*, but have non-matching 'title' and 'short name' fields.

**Comment by foglabs-zen** [comment]
Rather than switch to 'short name', we could instead batch-edit the SCCtv records in AMS2 to have 'Seattle Colleges Cable Television' as their holding_organization, and simply push to AAPB.

If we go this way, we probably still want to analyze whether any other orgs are missing due to this problem.

**Comment by singlesoliloquy** [comment]
How many orgs have short names different than name title for list page?
