### ISSUE TITLE
Exhibit 'View Records From Exhibit Section' Button Does Not Work

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2233]
Because:
The 'view records in exhibit section' button displayed in exhibit subsections yields an empty search when clicked. The top-level 'View records from exhibit' button *does* work as intended. This is because, while creative's design for exhibits made this distinction between linked records  for 'exhibits' vs. 'exhibit sections', the distinction was never made in the metadata.

![Screen Shot 2021-04-15 at 2.04.10 PM.png](https://images.zenhubusercontent.com/5d2cc7e91325bafe06bc11ae/d31a375e-b795-44c0-b758-38e9badd8bc0)
![Screen Shot 2021-04-15 at 2.03.28 PM.png](https://images.zenhubusercontent.com/5d2cc7e91325bafe06bc11ae/f61cb43d-0397-4227-b9c1-d532274df875)

Done When:
'View Records From Exhibit Section' button is replaced with 'View Records From Exhibit' button. Because record metadata currently connects a record to an exhibit (not an exhibit section), and the 'records from exhibit' code ignores this distinction, and a given exhibit section *could* have no records associated with it, I think it makes the most sense to just remove this apparent functionality and solidify that the 'View Records...' button simply brings you to a search with all of the records in the exhibit.

**Comment by singlesoliloquy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MLA-Developers-5d0a8ef27c5752598acebdb1/issues/WGBH-MLA/AAPB2/2233?planning-poker) with ZenHub @afred @foglabs-zen @jasoncorum

**Comment by singlesoliloquy** [comment]
This is working now. Jason fixed it.
