### ISSUE TITLE
Add podcast next to "AAPB on Facebook: below "From the Blog" section on homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2324]
## User Story
As a user, I should be able to click a link that says "AAPB podcast" which appears next to AAPB on Facebook below "From the Blog" on the homepage.

## Done Looks Like
A user can click a link that says "AAPB podcast" which appears next to AAPB on Facebook below "From the Blog" on the homepage.

**Comment by caseyedavis12** [comment]
@foglabs @singlesoliloquy can you work on this soon?

**Comment by caseyedavis12** [comment]
@foglabs @singlesoliloquy we discussed this at a recent AAPB team meeting and are wondering if the podcast name/logo could be added to the AAPB header so that the link travels across the website. Also, it would be great to add the link to the homepage as described above. Thanks!

**Comment by singlesoliloquy** [comment]
Is this closed since it's on the footer now?
