### ISSUE TITLE
Exhibit Sort by Year shows Relevance Button Instead

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2376]
**Describe the bug**
On an exhibit where records are sorted by Date Ascending (as in Latino Empowerment: https://americanarchive.org/catalog?f%5Bexhibits%5D%5B%5D=latino-empowerment&sort=year+asc&f[access_types][]=online) the button that appears on the search results says "Relevance" rather than "Date (oldest)"

**To Reproduce**
Go to Latino Empowerment Exhibit. Click View All Exhibit Records. See URL where it says Sort=year+asc and then see button that says Relevance.

**Expected behavior**
Sort button should accurately reflect how records are being sorted.

**Additional context**
LOC has inquired about this twice.

**Comment by mrharpo** [comment]
Fixed with #2488
