### ISSUE TITLE
Iframe Proportions Are Incorrect For Some Screen Sizes

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/AAPB2#2435]
Because:
At certain viewport proportions, exhibit iframes with the "exhibit-small-iframe" cut off the content:

![Screen Shot 2022-05-24 at 9.20.48 AM.png](https://images.zenhubusercontent.com/5d2cc7e91325bafe06bc11ae/054b9438-cb54-4f34-8272-65330d0b147a)

Done When:
"exhibit-small-iframe" Exhibit iframes are appropriately proportioned and centered within the exhibit's main column.

**Comment by mrharpo** [comment]
Duplicate of #2432
