### ISSUE TITLE
Adding AAPB Banner to Sesame Street Seasons 1-14

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/AAPB2#2443]
## User Story

Sesame Street Seasons 1-14 have been added to the AAPB, however they don't yet have the banner telling folks why items are restricted! I've attached a list of GUIDs needing the banner (the same banner that's on all other seasons of Sesame Street on AAPB (this is a good reference: https://americanarchive.org/catalog/cpb-aacip-530-0000001555))

## Additional Information

[https://app.zenhub.com/files/26285120/112e812a-f24e-4fc7-8fe3-540b5f1df8d0/download](https://app.zenhub.com/files/26285120/112e812a-f24e-4fc7-8fe3-540b5f1df8d0/download)

## Done Looks Like

![Screen Shot 2022-06-27 at 11.41.10 AM.png](https://images.zenhubusercontent.com/5fd38131b736e215633119d4/2a3bb30e-280b-410e-bd68-c3f4214e1ae2)

**Comment by mrharpo** [comment]
Closed with #2441
