### ISSUE TITLE
Conducting searches with quotes yields results that don't include transcript snippets

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2453]
**Describe the bug**
When a user conducts a search with quotes around the search term, retrieved results do not show where those keywords appear in transcripts. If you do the same search without quotes, search results show transcript snippets.

**Expected behavior**
Searches for terms in quotes should include results that show transcript snippets.

**Comment by mrharpo** [comment]
Looking into this:

When searching for `"ice cream"`:
https://americanarchive.org/catalog?f%5Bspecial_collections%5D%5B%5D=backstory&per_page=10&q=%22ice+cream%22&utf8=%E2%9C%93&f[access_types][]=online

# `GET /snippets.json?`
The request form data is being sent as such:
## Form Data
```yml
ids[]: cpb-aacip-532-3775t3h512
ids[]: cpb-aacip-5a4ab819222
ids[]: cpb-aacip-532-t43hx1758w
ids[]: cpb-aacip-af60440fe9c
ids[]: cpb-aacip-cca5af185c1
ids[]: cpb-aacip-532-c53dz0493w
ids[]: cpb-aacip-532-h41jh3fc4q
ids[]: cpb-aacip-532-n29p26rf2k
ids[]: cpb-aacip-532-jq0sq8rs78
ids[]: cpb-aacip-41541e17829
query: &quot;&quot;
```
So the quotes are not properly sent from the search form.

**Comment by mrharpo** [comment]
# JS / ERB
https://github.com/WGBH-MLA/AAPB2/blob/8aebfd3fbc6554996662b0f1bb8120a06acdcd58/app/views/catalog/index.html.erb#L45-L50

The double quotes around the `@query` are breaking when the erb templating happens.

## Tests
`ice cream` => `"ice cream"`
`"ice cream"` => `"&quot;&quot;"`
`"ice cream` => 500 error
`'ice cream` => `"&#39;ice cream"`
`'ice cream'` => `"&#39;ice cream&#39;"`

## Escaping
Tried many combinations, including: 
- Escaping with single quotes `'`
- Escaping with backticks ``` ` ```
- Unescaping
- Using `raw()`
- Using `html_escape()`
- Multiple of the above
- Several others I've forgotten

So far, none yield the expected results.

**Comment by mrharpo** [comment]
# catalog_controller
https://github.com/WGBH-MLA/AAPB2/blob/8aebfd3fbc6554996662b0f1bb8120a06acdcd58/app/controllers/catalog_controller.rb#L195-L197

With pry:
```ruby
> params
=> {"utf8"=>"✓", "f"=>{"access_types"=>["online"]}, "per_page"=>"100", "q"=>"\"ice cream\"", "controller"=>"catalog", "action"=>"index"}
> params[:q]    
=> "\"ice cream\""
params[:q].dup
=> "\"ice cream\""
@query
=> "\"\""
@terms_array
=> [["ICE", "CREAM"]]
```

# Questions
- How is `@query` empty if `params[:q].dup=> "\"ice cream\""` ?
- How did `@terms_array` get `[["ICE", "CREAM"]]` from that?

**Comment by mrharpo** [comment]
# Some answers
1+2. `@query` is `"\"ice cream\""` before line 197, and `"\"\""` afterwards.

# More questions
3. ??

**Comment by mrharpo** [comment]
# query_to_terms_array
After pairing with Drew, we decided this function is confusing.

https://github.com/WGBH-MLA/AAPB2/blob/8aebfd3fbc6554996662b0f1bb8120a06acdcd58/app/helpers/application_helper.rb#L13-L41

Current steps:
1. Read the list of stopwords
2. if query contains quotes:
  1. Get quoted terms
  2. Remove quoted terms from query
  3. Remove punctuation from remaining query
  4. Remove stop words from remaining query
3. Flatten quoted terms
4. Add remaining cleaned query terms
5. For each term:
  1. Uppercase
  2. Strip whitespace
  3. Remove all non word, non space characters
6. Return query terms array
