### ISSUE TITLE
Changing number of items per page on search results removes transcript snippets

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#2454]
**Describe the bug**
When you change the display from 10 to another number of items per search results page, the search results no longer includes the transcript snippet where the searched for term is highlighted. 

**Expected behavior**
Displays of more than 10 (or default) records per page should provide the same amount of information (including transcript snippets) as the default display.

**Comment by mrharpo** [comment]
@caseyedavis12 It appears to be working for me:

![aapb_test](https://user-images.githubusercontent.com/2718445/180307305-24441fa2-161e-44c7-91b1-e388d1bf805b.png)

Can you post an example?

**Comment by caseyedavis12** [comment]
Interesting. This seems to just be an issue when you are searching within a Special Collection.

Try this and switch to 100: https://americanarchive.org/catalog?f%5Bspecial_collections%5D%5B%5D=backstory&q=aids&utf8=%E2%9C%93&f[access_types][]=digitized

**Comment by mrharpo** [comment]
More intrigue! :detective: For just that one record:
- 10 - works
- 20 - works
- 50 - doesn't work
- 100 - doesn't work

However, the other results on that page are also producing inconsistent behavior:
With 50 results:
![Screenshot from 2022-07-21 13-29-34](https://user-images.githubusercontent.com/2718445/180310308-bf107b6e-ee59-444b-88a3-2855bd9d8e64.png)

With 100 results:
![Screenshot from 2022-07-21 13-31-55](https://user-images.githubusercontent.com/2718445/180310323-88fe6a41-c74d-4f82-9e7c-12c1495c5b9e.png)
