### ISSUE TITLE
Bug: "D.C." not recognized in list of words to keep as all caps

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#2458]
### Reproduce
<img width="653" alt="image" src="https://user-images.githubusercontent.com/1507490/181019216-1d1ec78e-e6db-4620-9019-e79f70ef505d.png">
at the time of this writing this ☝️ is what shows up for [this record](https://americanarchive.org/catalog/cpb-aacip_507-p55db7wg1t).

### Background
there's an array of acronyms to keep as all-caps in `lib/scripts/cleaner.rb`. Just need to add `D.C.` to it.

**Comment by mrharpo** [comment]
Fixed with #2459
