### ISSUE TITLE
Make thumbnail that displays in email for AAPB URL the AAPB logo

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/AAPB2#2464]
**Is your feature request related to a problem? Please describe.**
Make thumbnail that displays in email for AAPB URL the AAPB logo. Currently, Phylis Schlafly shows up.

**Done When**
The AAPB logo is grabbed when the URL is copied and pasted in email and social media.

![Screen Shot 2022-08-24 at 9.54.22 AM.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/845486fa-7dc6-430c-815e-fdb5220753ee)

**Comment by mrharpo** [comment]
Closed with #2467
