### ISSUE TITLE
BUG: JSON API endpoint for catalog records doesn't work with old-style AAPB IDs having underscore

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#2773]
### Replicate
* New style with dash works: https://americanarchive.org/api/cpb-aacip-512-707wm14j8q.json
* Old style with underscore doesn't: https://americanarchive.org/api/cpb-aacip_512-707wm14j8q.json

### Done when
Links with old-style IDs work.

### Background
The `IdHelper` class in `/app/helpers/id_helper.rb`  is used to solve this problem for non-API URLs:
* New style works: https://americanarchive.org/catalog/cpb-aacip-512-707wm14j8q
* Old style also works: https://americanarchive.org/catalog/cpb-aacip_512-707wm14j8q

Notice that we don't do redirecting here. There are pros and cons to not redirecting, but I think right now staying consistent within the code probably has more net value than enforcing the canonical new-style URLs through redirection. So let's stay consistent by not redirecting unless somebody has a more compelling argument for switching to a redirection strategy.

**Comment by foo4thought** [comment]
this is not a bug; some IDs actually use the underscore and can be summoned using that explicitly or with a single-character wildcard.  
mylocal:~ kevin_carter$ curl -sS 'https://americanarchive.org/api.json?q=id:cpb-aacip_*&fl=id&rows=1&start=0'
{
  "responseHeader": {
    "status": 0,
    "QTime": 283,
    "params": {
      "q": "id:cpb-aacip_*",
      "fl": "id",
      "start": "0",
      "rows": "1",
      "wt": "ruby"
    }
  },
  "response": {
    "numFound": 2253000,
    "start": 0,
    "docs": [
      {
        "id": "cpb-aacip_211-70msbxxf"
      }
    ]
  }
}

**Comment by foo4thought** [comment]
oof - I see you're using a different method.  I guess that's a bug but I always use the parameter `q=`
