### ISSUE TITLE
MAP: incorrect name and location

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/AAPB2#2813]
### Description

The National Archives is in Washington State and is incorrectly listed as “National Records and Archives Administration”. It should be “National Archives and Records Administration” and should be located in Washington, D.C. 

### Reproduction steps

Go to https://americanarchive.org/
Zoom into Washington state
Locate NARA

### Expected behavior

Be in Washinton, D.C. and be called National Archives and Records Administration

**Comment by mrharpo** [comment]
@ekemeyer I moved them on the map, but they are still listed in the index as `National Records and Archives Administration`: https://americanarchive.org/catalog?f%5Bcontributing_organizations%5D%5B%5D=National+Records+and+Archives+Administration+%28DC%29&f[access_types][]=online

```xml
<instantiationAnnotation annotationType="organization">National Records and Archives Administration</instantiationAnnotation>
```

We will need to change the PBCore and push the records for them to show up correctly.
