### ISSUE TITLE
Putting up replacement transcript for cpb-aacip-058470b9940

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/AAPB2#2822]
# Details 
The Bill Moyers folks sent us an updated transcript for cpb-aacip-058470b9940, do you mind putting it into the S3 so that it appears on the AAPB?

Submitted by: Miranda
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
- Copied file as requested to S3 for AAPB 
- copied file to backups/transcripts/cpb-aacip-058470b9940/cpb-aacip-058470b9940-transcript.txt
- reindexed on AAPB
- reindexed in AAPB_Enhancements
- confirmed quality in AAPB web
