### ISSUE TITLE
get ci.yml to stick after redeploys

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/AAPB2#380]
@afred : Thoughts on ci.yml?
- Let it be shared across deployments. (After it is put in place by hand once.)
- or, put it in place as part of the deployment process.
- or, ...?

**Comment by afred** [comment]
Yes

Part of the deployment process should include being able to set the things that are shared between deployments.

I'm leaning toward a a set of cap recipes such as `deploy:ci_config`, `deploy:db_config`, `deploy:app_secret`, `deploy:redis_config`. The goal being to put sensitive data (secrets and config) into their appropriate location on production servers. Most often that location is the "shared" directory that is shared across deployments.

The sensitive data could come from a protected repository (e.g. Stash). Or we could have capistrano prompt the user at runtime. Or read from a local file. Whatever makes the most sense.

**Comment by mccalluc** [comment]
@Muraszko : Here's what I understand:
- Private information which is part of the build: I think this taken care of by our private repo on Stash, which includes ci.yml: https://atlas.wgbh.org/stash/projects/MLA/repos/aapb_deployment/browse/config/ci.yml
- Making sure it is preserved across deploys: I think that is what the shared directory is for, and on both instances, it's in place:
```
$ for IP in `ruby scripts/ssh_opt.rb --name aapb.wgbh-mla.org --ips_by_tag`; do ssh ec2-user@$IP -i ~/.ssh/aapb.wgbh-mla.org.pem 'ls /var/www/aapb/shared/config'; done
ci.yml
database.yml
secrets.yml
ci.yml
database.yml
secrets.yml
```
- Here's where I'm confused: it seems like `shared` might just be a convention, and you also need a configuration in capistrano, but that seems to be in place, too:
```
$ grep linked_files -r . 
./config/deploy.rb:# Default value for :linked_files is []
./config/deploy.rb:set :linked_files, fetch(:linked_files, []).push('config/database.yml', 'config/secrets.yml', 'config/ci.yml')
```
