### ISSUE TITLE
Will multi videos ever have captions?

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/AAPB2#489]
With an incoming PR, I'm merging the logic to show multiple videos, and to show captions. I don't want to over-complicate things, so for right now it still assumes there is only one caption file... but if there are multiple, we need to iterate over the arrays in parallel, and more importantly we need to be sure that the source pbcore also maintains the same parallel order. 

If we can assure ourselves that the AMS will return both in the correct order (@foo4thought?) , tweaking the `_player` partial for parallel iteration isn't a big job.

**Comment by sroosa** [comment]
@mccalluc How are you establishing the order that the videos will play in?

**Comment by mccalluc** [comment]
The site just shows them in the order the AMS provides the Ci IDs, but there is no assurance these will be in order.
