### ISSUE TITLE
Get monitor.us working for media urls

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#507]
(This is Chuck clarifying:)
We want monitor.us to do two things for us:
- Make sure media can be served to US browsers (if the refer header is there).
- and make sure it doesn't get served to non-US.

Right now reporting an error for http://americanarchive.org/media/cpb-aacip_147-78gf23gn

**Comment by caseyedavis12** [comment]
This asset is playing in the AMS and has a Sony Ci id.

https://ams.americanarchive.org/records/details/2959779
