### ISSUE TITLE
Avoid http 500s for routes that should be 404s

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/AAPB2#806]
**To reproduce:** Go to http://americanarchive.org/foo. This should be treated like a 404.

**done when** unhandled routes return 404 instead of 500

**Comment by mccalluc** [comment]
When I start my local server in production mode I see this in the log:
```
Error during failsafe response: Missing partial shared/_ajax_modal with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/Users/chuck_mccallum/starting/AAPB2/app/views"
  * "/Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353@aapb/gems/blacklight_range_limit-5.1.0/app/views"
  * "/Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353@aapb/gems/blacklight-gallery-0.3.0/app/views"
  * "/Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353@aapb/gems/blacklight-5.11.1/app/views"
  * "/Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353@aapb/gems/kaminari-0.16.3/app/views"
```
(It is recognized as a 404 in development, and that process starts on production, but it breaks midway through.)

**Comment by mccalluc** [comment]
The `formats` is weird: It's looking for  `_ajax_modal.css`?

**Comment by mccalluc** [comment]
Farther down in the log there's another error on this same request:
>
Error during failsafe response: Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.

I am not getting anywhere on this.
