### ISSUE TITLE
Pacifica Radio Archives dates

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#821]
From Alan: dates of creation and broadcast are in the Pacifica website, but not in AAPB unless we put them in manually. 

@sroosa: Can we put an intern on this?

**Comment by sroosa** [comment]
@caseyedavis12 Yes, I can have an intern start on this. Should I just have them do the Pacifica things in the ORR, or all of them?

**Comment by caseyedavis12** [comment]
@sroosa: Let's start with Pacifica and then add WGBH dates. I have dates for most of the WGBH series that we put in the ORR. Maybe those could be inserted by Kevin.

**Comment by sroosa** [comment]
@caseyedavis12 Do you have a one-to-one correlation between those dates and the records, like a matching GUID? And are the dates formatted the way we want? We'd just want to check that before we added anything.

**Comment by caseyedavis12** [comment]
@sroosa: Yep, If you go to the Pacifica Radio Archives website and go to "Search our Collection" then "search by Archive Number" and paste the Unique Identifier listed in our metadata record with source="unknown" it will retrieve that record.


http://www.pacificaradioarchives.org/search-by-number


Here is an example of the archive number: BB2531

**Comment by sroosa** [comment]
@caseyedavis12 I meant for the WGBH records.

**Comment by caseyedavis12** [comment]
@sroosa: Oh! No, they are not formatted the way we want. For example, one series I know was produced between 1958 - 1959 but I do not know the date of the broadcast.

We don't have a one-to-one correlation between GUIDs. I just have series and date.

**Comment by sroosa** [comment]
@caseyedavis12 So that would definitely take some more work on my end before we could hand it off to Kevin. I could see us pulling GUIDs for series, adding the appropriate year formatted YYYY-01-01 in a column on a spreadsheet. From that Kevin could write to script to add Asset Dates. We could not handle any kind of range information, currently, so we'd need to pick one year for each asset. Not sure how clean/accurate that would be, but on the other hand, it might be better than no dates.

**Comment by mccalluc** [comment]
@sroosa: probably shouldn't have jumped on this, but here's a script
```ruby
require 'json'
require 'nokogiri'
require 'open-uri'

(0..3).map{|i| i*100}.each do |offset|
  uri = "http://americanarchive.org/api.json?fl=id,title,xml&q=organization:%22Pacifica+Radio+Archives+%28CA%29%22&rows=100&offset=#{offset}"
  json_string = URI.parse(uri).read
  JSON.parse(json_string)['response']['docs'].map{|doc| doc['xml']}.each do |xml_string|
    doc = Nokogiri::XML(xml_string).remove_namespaces!
    aapb_id = doc.xpath('//pbcoreIdentifier[@source="http://americanarchiveinventory.org"]').text
    p_id = doc.xpath('//pbcoreIdentifier[@source="unknown"]').text
    p_uri = "http://www.pacificaradioarchives.org/recording/#{p_id.downcase.gsub(/\W/,'')}"
    html = URI.parse(p_uri).read
    p_doc = Nokogiri::HTML(html)
    recorded_on = p_doc.css('.field-name-field-recordedon-raw').text.sub(/.*?:/,'').gsub(/\s+/,' ')
    broadcast_on = p_doc.css('.field-name-field-broadcaston-raw').text.sub(/.*?:/,'').gsub(/\s+/,' ')
    puts [aapb_id, p_id,recorded_on,broadcast_on].join("\t")
    sleep 1
  end
end
```
and here's a bit of the output
```
cpb-aacip/28-ft8df6kf9j BB1783     1968-01-26     1968-03-26
cpb-aacip/28-b27pn8xp73 BB2369     Dec. 1969.     7 Jan. 1970.
cpb-aacip/28-696zw18x5x BC0483     1971-11~       KPFA, 27 Feb. 1972.
cpb-aacip/28-2j6833n53x AZ0090     NULL           KPFA, Apr. 1977.
cpb-aacip/28-xs5j960v3v BB0063     1960-09-01     KPFA, 1 Sept. 1960.
```

soapbox: We really need to recognize mechanical tasks when we see them, and where it's something small like this, I really do think that librarians and librarians-in-training need to have a handle on the appropriate tools for the job.
