### ISSUE TITLE
Consider turning off turbolinks

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/AAPB2#861]
This is the reason the page just seems to stall when you click on a link: It's actually an AJAX request under the hood, rather than a real page load, so you don't get normal browser feedback while the page loads.

--> Try turning off turbo links: Might be a tad bit slower for complete page load, but the subjective experience may be better: browser feedback that the page is loading, and we may get partial rendering as the bytes arrive rather than waiting for the whole thing. We'll need to be sure we have all the HTTP caching set correctly.

**Comment by sroosa** [comment]
Similar to what we did here, but in general? 
https://github.com/WGBH/AAPB2/pull/1109
