### ISSUE TITLE
Clarify embeds or remove

### ISSUE THREAD

**Issue by mccalluc** [WGBH-MLA/AAPB2#871]
We need to either clarify the requirements for embeds or remove them. They are available right now: http://americanarchive.org/embed/cpb-aacip_37-16c2fsnr

Access restrictions could go in a number of directions:
- We might allow/deny based on characteristics of the requester (like the existing geoblocks)
- We might allow/deny based on a list of allowed embedding sites using [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options)
- We might allow/deny based on characteristics of the media (like the org)

@caseyedavis12 ?

**Comment by caseyedavis12** [comment]
@mccalluc:

--We should use the existing geo-blocks to allow/deny based on the characteristics of the requester.
--For now, I don't think we should use the X-Frame-Options - we will want to embed on sites other than AAPB (like our Wordpress blog), and we don't know what other origins we will want to allow to embed in the future.
--Same for question number 3.

Is there a way that we can put the AAPB logo with a link back to the record page in the video player, which would appear at the beginning and the end of the embedded program?
