### ISSUE TITLE
Cookies warning after Rules of Use click-through

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/AAPB2#877]
Issue submitted by an AAPB user via Twitter:

For those blocking cookies, clicking through the terms page refreshes the terms page without any kind of error warning about cookies.

**Comment by mccalluc** [comment]
@caseyedavis12 : I can't quite tell what the user is seeing, and I'm not sure what the desired end result is.

If I disable cookies locally, and try to click through terms on localhost I get InvalidAuthenticityToken. When I get home I can try hitting the real site. (In the office, we never get terms from the live site.)

If someone has disabled cookies, they should realize that sessioning is not going to work on most websites: This is not a case I'm inclined to bend over backwards for.
